### ISSUE TITLE
Docs: lt-expand and :>/:<

### ISSUE THREAD

**Issue by Badestrand** [jimregan/lttoolbox#40]
Hi

great toolset, thank you very much!

Is there documentation somewhere on what the :> and :< parts mean after expanding a dictionary? I couldn't find anything.

On this page (http://wiki.apertium.org/wiki/Finding_errors_in_dictionaries) I see they are filtering those lines out - are they useless?

Thank you!

edit: It seems to have to do with the LR/RL tags but I also don't know what these are for..

**Comment by unhammer** [comment]
See http://wiki.apertium.org/wiki/LR 

An entry with r="LR" in the .dix will get `:>:` when expanding, RL gets `:<:`, others get `:`. In analysers, LR is often used for alternative forms that all map into the same analysis. When making a generator from the same .dix file, the LR's are stripped out, so one analysis will only get one form.

**Comment by unhammer** [comment]
btw, note that the upstream of this is at https://svn.code.sf.net/p/apertium/svn/trunk/lttoolbox/ (more info at http://wiki.apertium.org/wiki/Installation )

**Comment by Badestrand** [comment]
Ah I see, thank you very much!
